"""creating user and thread table

Revision ID: 3d76b8121f55
Revises: 51597028f6a8
Create Date: 2026-03-25 16:15:24.529698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d76b8121f55'
down_revision: Union[str, Sequence[str], None] = '51597028f6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Chats', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Chats', type_='unique')
    # ### end Alembic commands ###
