"""fixed chats table

Revision ID: 52ad64fb7c23
Revises: 69a83bb0b45a
Create Date: 2026-03-27 17:06:55.780732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ad64fb7c23'
down_revision: Union[str, Sequence[str], None] = '69a83bb0b45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chats', sa.Column('title', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'Chats', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Chats', type_='unique')
    op.drop_column('Chats', 'title')
    # ### end Alembic commands ###
